### ISSUE TITLE
getInfo() method throws exception.

### ISSUE THREAD

**Issue by iampolo87** [element119/module-admin-redis-report#4]
Magento EE (cloud) 2.4.6-p4 is throwing the following exception, not sure why its instantiating RemoteSynchronizedCache::getInfo() but the module is not working.

**report.CRITICAL: Error**: Call to undefined method Magento\Framework\Cache\Backend\RemoteSynchronizedCache::getInfo() in /vendor/element
119/module-admin-redis-report/Model/RedisInfo.php:189

**Comment by pykettk** [comment]
Thanks for the report! I'll try to make some time to investigate this over the weekend 🤞

**Comment by pykettk** [comment]
I've been unable to replicate this on a blank Adobe Commerce 2.4.6-p4 instance, @iampolo87 . I suspect we may have Redis configured differently, hence the difference in results. Can you please share which class(es) are defined in your `env.php` file under the `backend` key - here's a screenshot from my local development environment to clarify what I'm talking about.

![redis-config](https://github.com/user-attachments/assets/63d1b2eb-2618-45ff-b8c5-43014fc4e106)

**Comment by iampolo87** [comment]
Hey, thanks for the fast reply i was on vacation. So, i've tried it again today and it worked like a charm, honestly have no idea what happened last time.
You can safely ignore this issue, sorry and thanks again!
